
storage: ../storage/data
auth:
  htpasswd:
    file: ../storage/htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@lamk/*':
    access: $all
    publish: $all
    proxy: npmjs
  '**':
    proxy: npmjs
logs:
  - {type: stdout, format: pretty, level: http}