domain = "lamk.work"
artifacts-subdomain = "artifacts.lamk.work"
droplets-tags = ["stg"]
project-name="lamk-stg"
artifacts-name="lamk-artifacts-stg"
environment="Staging"
agnesa-domain="agnesa-test.lamk.tech"
nestpay-api-endpoint="https://entegrasyon.asseco-see.com.tr/fim/api"
nestpay-gateway-endpoint="https://entegrasyon.asseco-see.com.tr/fim/est3Dgate"
