import v8n from 'v8n';

export const defaultSchemaEntries = {
   // ID is optional as it is autogenerated by server on creation.
   _id: v8n().optional(
    v8n().id(),
    true,
  ),

   // createdAt is optional as it is added by server on creation.
   createdAt: v8n().optional(
    v8n().datetime(),
    true,
  ),
  modifiedAt: v8n().optional(
    v8n().datetime(),
    true,
  ),
}

export interface DefaultSchema { 
  _id: string;
  createdAt: string;
  modifiedAt: string;
}