import { Application } from '@feathersjs/feathers';
import { authentication } from '../../services/authentication/authentication';
import { stores } from '../../services/stores/stores';
import { products } from '../../services/products/products';
import { orders } from '../../services/orders/orders';
import { artifacts } from '../../services/artifacts/artifacts';
import { deliveries } from '../../services/deliveries/deliveries';
import { users } from '../../services/users/users';
import { authManagement } from '../../services/authManagement/authManagement';
import { carts } from '../../services/carts/carts';
import { addresses } from '../../services/addresses/addresses';
import { categories } from '../../services/categories/categories';
import { storeCategories } from '../../services/store-categories/storeCategories';
import { storeContents } from '../../services/store-contents/storeContents';
import { email } from '../../services/email/email';
import { search } from '../../services/search/search';
import { productGroups } from '../../services/product-groups/productGroups';
import { campaigns } from '../../services/campaigns/campaigns';
import { storeAnalytics } from '../../services/store-analytics/storeAnalytics';
import { storePaymentMethods } from '../../services/store-payment-methods/storePaymentMethods';
import { orderPayments } from '../../services/order-payments/orderPayments';
import { orderPaymentsQuery } from '../../services/order-payments-query/orderPaymentsQuery';
import { contactUs } from '../../services/contact-us/contactUs';

export const registerServices = (app: Application) => {
  authentication(app);
  stores(app);
  products(app);
  orders(app);
  deliveries(app);
  artifacts(app);
  users(app);
  authManagement(app);
  carts(app);
  addresses(app);
  categories(app);
  storeCategories(app);
  storeContents(app);
  email(app);
  search(app);
  productGroups(app);
  campaigns(app);
  storeAnalytics(app);
  storePaymentMethods(app);
  orderPayments(app);
  orderPaymentsQuery(app);
  contactUs(app);
};
