version: '3.5'

# To speed up dev builds, check https://blog.rocketinsights.com/speeding-up-docker-development-on-the-mac/
# Good article on reverse proxy and dnsmasq: https://ianduffy.ie/blog/2019/02/22/local-development-with-virtual-hosts-and-https/
networks:
  main-network:
    driver: bridge

services:
  reverse-proxy:
    image: traefik:v2.1.1
    container_name: reverse-proxy-dev
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false # Don't expose all services by default, use `traefik.enable`
      - --entrypoints.web.address=:80
      - --entrypoints.web-secure.address=:443 
    ports:
       # The Web UI (enabled by --api.insecure=true)
       - "8080:8080"
       - "80:80"
       - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - data-api
      - store-ui
      - backstore-ui
      - object-store
    networks:
      - main-network

  object-store:
    image: minio/minio:RELEASE.2020-01-16T22-40-29Z
    container_name: object-store-dev
    command: server /data
    expose: 
      - 9000
    volumes:
      - ./data:/data
    networks:
      - main-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.object-store.priority=1000
      - traefik.http.routers.object-store.rule=Host(`artifacts.dev.sradevski.com`)
      - traefik.http.services.object-store.loadbalancer.server.port=9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123

  data-api:
    image: lamk/data-api-dev
    build: 
      context: ./packages/data-api
      target: dev
      args: 
        - GPR_TOKEN=$GPR_TOKEN
    container_name: data-api-dev
    volumes:
      - ./packages/data-api:/usr/src/app:delegated
      - /usr/src/app/node_modules #don't bind node_modules, speeding up hot reloads
    networks:
      - main-network
    expose: 
      - 80
    ports:
      - 9229:9229 #debug port
    labels:
      - traefik.enable=true
      - traefik.http.routers.data-api.priority=1000
      - traefik.http.routers.data-api.rule=Host(`api.dev.sradevski.com`)
      - traefik.http.services.data-api.loadbalancer.server.port=80 
    environment: 
      GPR_TOKEN: $GPR_TOKEN
      PORT: 80
      HOST: "api.dev.sradevski.com"
      JWT_SECRET: "1234dev"
      MONGODB_DB_NAME: db
      MONGODB_CONNECTION_STRING: "mongodb+srv://dev-user:ou1ewM4eGQH1lxLq@dev-6oiee.mongodb.net/test?retryWrites=true&w=majority"
      STORAGE_BUCKET_NAME: dev-bucket
      STORAGE_ENDPOINT: "artifacts.dev.sradevski.com"
      STORAGE_ACCESS_KEY_ID: minio
      STORAGE_ACCESS_KEY_SECRET: minio123
    
  store-ui:
    image: lamk/store-ui-dev
    build: 
      context: ./packages/store-ui
      target: dev
      args: 
        - GPR_TOKEN=$GPR_TOKEN
    container_name: store-ui-dev
    depends_on: 
      - data-api
    volumes:
      - ./packages/store-ui:/usr/src/app:delegated
      - /usr/src/app/node_modules #don't bind node_modules, speeding up hot reloads
    networks:
      - main-network
    expose: 
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.store-ui.priority=1 #Set to low priority so our services resolve before stores
      - traefik.http.routers.store-ui.rule=HostRegexp(`{subdomain:.+}.dev.sradevski.com`, `local-agnesa-test.lamk.tech`)
      - traefik.http.services.store-ui.loadbalancer.server.port=80 
    environment: 
      GPR_TOKEN: $GPR_TOKEN
      API_ENDPOINT: "http://api.dev.sradevski.com"
      # The bucket name is required for minio, but the CDN URL in production points to the bucket, not to the storage.
      ARTIFACTS_ENDPOINT: "http://artifacts.dev.sradevski.com/dev-bucket"
      ANALYTICS_TRACKING_ID: '' 
      PORT: 80

  backstore-ui:
    image: lamk/backstore-ui-dev
    build: 
      context: ./packages/backstore-ui
      target: dev
      args: 
        - GPR_TOKEN=$GPR_TOKEN
    container_name: backstore-ui-dev
    depends_on: 
      - data-api
    volumes:
      - ./packages/backstore-ui:/usr/src/app:delegated
      - /usr/src/app/node_modules #don't bind node_modules, speeding up hot reloads
    networks:
      - main-network
    expose: 
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.backstore-ui.priority=1000
      - traefik.http.routers.backstore-ui.rule=Host(`back.dev.sradevski.com`)
      - traefik.http.services.backstore-ui.loadbalancer.server.port=80 
    environment:
      GPR_TOKEN: $GPR_TOKEN
      REACT_APP_API_ENDPOINT: "http://api.dev.sradevski.com"
      # The bucket name is required for minio, but the CDN URL in production points to the bucket, not to the storage.
      REACT_APP_ARTIFACTS_ENDPOINT: "http://artifacts.dev.sradevski.com/dev-bucket"
      PORT: 80