version: '3.5'

# This is an example setup that would work in production, although it is not really useful for multi-server setup.
# To speed up dev builds, check https://blog.rocketinsights.com/speeding-up-docker-development-on-the-mac/
# Good article on reverse proxy and dnsmasq: https://ianduffy.ie/blog/2019/02/22/local-development-with-virtual-hosts-and-https/
networks:
  main-network:
    driver: bridge

services:
  reverse-proxy:
    image: traefik:v2.1.1
    container_name: reverse-proxy
    restart: always
    command:
      # - --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false # Don't expose all services by default, use `traefik.enable`
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      
      # The DNS challenge requires you to have a DO_AUTH_TOKEN environment variable set.
      # - --certificatesresolvers.cert-resolve.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.cert-resolve.acme.email=sradevski@live.com
      - --certificatesresolvers.cert-resolve.acme.storage=/certs/acme.json
      - --certificatesresolvers.cert-resolve.acme.dnsChallenge=true
      - --certificatesresolvers.cert-resolve.acme.dnsChallenge.provider=digitalocean
      - --certificatesresolvers.cert-resolve.acme.dnsChallenge.delayBeforeCheck=20

      # - --certificatesresolvers.custom-certs.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.custom-certs.acme.email=sradevski@live.com
      - --certificatesresolvers.custom-certs.acme.storage=/certs/customcert.json
      - --certificatesresolvers.custom-certs.acme.httpChallenge=true
      - --certificatesResolvers.custom-certs.acme.httpChallenge.entryPoint=web
    ports:
       - "80:80"
       - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /certs:/certs
    depends_on:
      - data-api
      - store-ui
      - backstore-ui
      - search
    networks:
      - main-network
    environment:
      # This is needed by Traefik to do proper let's encrypt DNS challenge.
      DO_AUTH_TOKEN: ${DIGITALOCEAN_TOKEN}

  search:
    image: typesense/typesense:0.14.0
    container_name: search
    command: ./typesense-server
    expose:
      - 8108
    volumes:
      - /search-data:/search-data
    networks:
      - main-network
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.search-https.redirectscheme.scheme=https

      - traefik.http.routers.search-http.priority=1000
      - traefik.http.routers.search-http.entrypoints=web
      - traefik.http.routers.search-http.rule=Host(`search.${SYSTEM_TLD}`)
      - traefik.http.routers.search-http.middlewares=search-https

      - traefik.http.routers.search.priority=1000
      - traefik.http.routers.search.rule=Host(`search.${SYSTEM_TLD}`)
      - traefik.http.services.search.loadbalancer.server.port=8108
      - traefik.http.routers.search.entrypoints=websecure
      - traefik.http.routers.search.tls=true
      # The store-ui domain is more generic, so a single definition for all subdomains is enough for the cert.
      # - traefik.http.routers.search.tls.certresolver=cert-resolve
      # - traefik.http.routers.search.tls.domains[0].main=search.${SYSTEM_TLD}
    environment:
      TYPESENSE_DATA_DIR: /search-data
      TYPESENSE_API_KEY: $SEARCH_SERVICE_API_KEY

  data-api:
    image: lamk/data-api:1.0.69
    container_name: data-api
    restart: always
    networks:
      - main-network
    expose: 
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.data-api-https.redirectscheme.scheme=https
      
      - traefik.http.routers.data-api-http.priority=1000
      - traefik.http.routers.data-api-http.entrypoints=web
      - traefik.http.routers.data-api-http.rule=Host(`api.${SYSTEM_TLD}`)
      - traefik.http.routers.data-api-http.middlewares=data-api-https

      - traefik.http.routers.data-api.priority=1000
      - traefik.http.routers.data-api.rule=Host(`api.${SYSTEM_TLD}`)
      - traefik.http.services.data-api.loadbalancer.server.port=80 
      - traefik.http.routers.data-api.entrypoints=websecure
      - traefik.http.routers.data-api.tls=true
      # The store-ui domain is more generic, so a single definition for all subdomains is enough for the cert.
      # - traefik.http.routers.data-api.tls.certresolver=cert-resolve
      # - traefik.http.routers.data-api.tls.domains[0].main=api.${SYSTEM_TLD}
    environment: 
      PORT: 80
      HOST: ${SYSTEM_TLD}
      JWT_SECRET: $JWT_SECRET
      MONGODB_DB_NAME: db
      MONGODB_CONNECTION_STRING: $MONGODB_CONNECTION_STRING
      STORAGE_ENDPOINT: fra1.digitaloceanspaces.com
      STORAGE_BUCKET_NAME: $STORAGE_BUCKET_NAME
      STORAGE_ACCESS_KEY_ID: $SPACES_ACCESS_KEY_ID
      STORAGE_ACCESS_KEY_SECRET: $SPACES_SECRET_ACCESS_KEY
      MAIL_SERVICE_API_KEY: $MAIL_SERVICE_API_KEY
      SEARCH_SERVICE_API_KEY: $SEARCH_SERVICE_API_KEY
      SEARCH_SERVICE_ENDPOINT: search.${SYSTEM_TLD}
      NESTPAY_API_ENDPOINT: $NESTPAY_API_ENDPOINT
      ANALYTICS_TRACKING_ID: $ANALYTICS_TRACKING_ID
      ANALYTICS_SECRET_KEY: $ANALYTICS_SECRET_KEY
      ENABLE_SIGNUP: "true"

  store-ui:
    image: lamk/store-ui:1.0.100
    container_name: store-ui
    restart: always
    depends_on: 
      - data-api
    networks:
      - main-network
    expose: 
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.store-ui-https.redirectscheme.scheme=https
      
      - traefik.http.routers.store-ui-http.priority=1
      - traefik.http.routers.store-ui-http.entrypoints=web
      - traefik.http.routers.store-ui-http.rule=HostRegexp(`{subdomain:.+}.${SYSTEM_TLD}`)
      - traefik.http.routers.store-ui-http.middlewares=store-ui-https
      - traefik.http.routers.store-ui-http.service=store-ui #never called due to redirect

      - traefik.http.routers.store-ui.priority=1 #Set to low priority so our services resolve before stores
      - traefik.http.routers.store-ui.entrypoints=websecure
      - traefik.http.routers.store-ui.rule=HostRegexp(`{subdomain:.+}.${SYSTEM_TLD}`)
      - traefik.http.routers.store-ui.service=store-ui
      - traefik.http.services.store-ui.loadbalancer.server.port=80

      - traefik.http.routers.store-ui.tls=true
      - traefik.http.routers.store-ui.tls.certresolver=cert-resolve
      - traefik.http.routers.store-ui.tls.domains[0].main=*.${SYSTEM_TLD}

      # Custom domains
      - traefik.http.middlewares.custom-domain-https.redirectscheme.scheme=https

      # middleware: https://www. to  https://
      - traefik.http.middlewares.trim_www.redirectregex.regex=^https://www\.(.+)
      - traefik.http.middlewares.trim_www.redirectregex.replacement=https://$${1}
      - traefik.http.middlewares.trim_www.redirectregex.permanent=false

      - traefik.http.routers.custom-domain-http.priority=1
      - traefik.http.routers.custom-domain-http.entrypoints=web
      - traefik.http.routers.custom-domain-http.rule=Host(${ESCAPED_CUSTOM_DOMAINS})
      - traefik.http.routers.custom-domain-http.middlewares=custom-domain-https
      - traefik.http.routers.custom-domain-http.service=custom-domain

      - traefik.http.routers.custom-domain.priority=1 #Set to low priority so our services resolve before stores
      - traefik.http.routers.custom-domain.entrypoints=websecure
      - traefik.http.routers.custom-domain.rule=Host(${ESCAPED_CUSTOM_DOMAINS})
      - traefik.http.routers.custom-domain.service=custom-domain
      - traefik.http.services.custom-domain.loadbalancer.server.port=80

      - traefik.http.routers.custom-domain.middlewares=trim_www

      - traefik.http.routers.custom-domain.tls=true
      - traefik.http.routers.custom-domain.tls.certresolver=custom-certs
      # This is just so we set something for a main domain, all other custom domains will be defined as sans
      - traefik.http.routers.custom-domain.tls.domains[0].main=demo.${SYSTEM_TLD}
      - traefik.http.routers.custom-domain.tls.domains[0].sans=${CUSTOM_DOMAINS}

    environment: 
      API_ENDPOINT: https://api.${SYSTEM_TLD}
      ARTIFACTS_ENDPOINT: https://artifacts.${SYSTEM_TLD}
      IMAGES_PROXY_ENDPOINT: https://${IMAGES_PROXY_ENDPOINT}
      ANALYTICS_TRACKING_ID: $ANALYTICS_TRACKING_ID 
      PORT: 80
      NESTPAY_GATEWAY_ENDPOINT: $NESTPAY_GATEWAY_ENDPOINT


  backstore-ui:
    image: lamk/backstore-ui:1.0.75
    container_name: backstore-ui
    restart: always
    depends_on: 
      - data-api
    networks:
      - main-network
    expose: 
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.backstore-ui-https.redirectscheme.scheme=https
      
      - traefik.http.routers.backstore-ui-http.priority=1000
      - traefik.http.routers.backstore-ui-http.entrypoints=web
      - traefik.http.routers.backstore-ui-http.rule=Host(`admin.${SYSTEM_TLD}`)
      - traefik.http.routers.backstore-ui-http.middlewares=backstore-ui-https

      - traefik.http.routers.backstore-ui.priority=1000
      - traefik.http.routers.backstore-ui.rule=Host(`admin.${SYSTEM_TLD}`)
      - traefik.http.services.backstore-ui.loadbalancer.server.port=80 
      - traefik.http.routers.backstore-ui.entrypoints=websecure
      - traefik.http.routers.backstore-ui.tls=true
      # - traefik.http.routers.backstore-ui.tls.certresolver=cert-resolve
      # - traefik.http.routers.backstore-ui.tls.domains[0].main=admin.${SYSTEM_TLD}
    environment: 
      REACT_APP_API_ENDPOINT: https://api.${SYSTEM_TLD}
      REACT_APP_ARTIFACTS_ENDPOINT: https://artifacts.${SYSTEM_TLD}
      REACT_APP_IMAGES_PROXY_ENDPOINT: https://${IMAGES_PROXY_ENDPOINT}
      REACT_APP_ENABLE_SIGNUP: "true"
      PORT: 80