apiVersion: v1
kind: Secret
metadata:
  name: test-secret
type: Opaque
data:
  # This should be base64 encoded and encrypted (not enabled by default)
  password: '123456'
  # When using, in the deployment env you need to say `valueFrom: secretKeyRef: name: key:`
