name: Publish packages

# This should be on pull request instead when the packages are more mature and there are more people working
on:
  push:
    branches: 
      - master
    paths:
      - packages/la-sdk/**
      - packages/blocks-ui/**
      - packages/translations/**

jobs:
  publish-gpr:
    name: Publish Package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ["blocks-ui", "la-sdk", "translations"]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@sradevski'
      - run: |
          LATEST=`npm view . version`
          CURRENT=`cat package.json | jq -r .version`
          if [ "$LATEST" != "$CURRENT" ]
          then
            echo Publishing "$CURRENT" version "${{ matrix.package }}" package.
            npm ci
            npm publish
          fi
          
        working-directory: ./packages/${{ matrix.package }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
