name: Publish services

on:
  push:
    branches: 
      - master
    paths:
      - packages/data-api/**
      - packages/store-ui/**
      - packages/backstore-ui/**

# Do a version check using https://hub.docker.com/v2/repositories/lamk/data-api/tags/ for LATEST to see if we need to publish
# After that, change the image tag to be "$CURRENT" instead.
#          LATEST=`get from DOCKERHUB`
#          CURRENT=`cat package.json | jq -r .version`
#          if [ "$LATEST" != "$CURRENT" ]
#          then
#           echo Publishing "$CURRENT" version "${{ matrix.package }}" service.
#          fi
   
jobs:
  publish-dockerfiles:
    name: Publish Service
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: ["data-api", "store-ui", "backstore-ui"]
    steps:
      - uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - run: |
          docker build . --file Dockerfile --build-arg GPR_TOKEN=${{secrets.GITHUB_TOKEN}} --tag lamk/"${{matrix.service}}":latest
          docker push lamk/"${{matrix.service}}":latest
        working-directory: ./packages/${{ matrix.service }}
