name: Publish services

on:
  push:
    branches: 
      - master
    paths:
      - packages/data-api/**
      - packages/store-ui/**
      - packages/backstore-ui/**

jobs:
  publish-dockerfiles:
    name: Publish Service
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: ["data-api", "store-ui", "backstore-ui"]
    steps:
      - uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - run: |
          DTOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'${{DOCKER_REGISTRY_USERNAME}}'", "password": "'${{DOCKER_REGISTRY_PASSWORD}}'"}' https://hub.docker.com/v2/users/login/ | jq -r .token)
              
          IMAGE_TAGS=$(curl -s -H "Authorization: JWT $DTOKEN" https://hub.docker.com/v2/repositories/lamk/${{matrix.service}}/tags/?page_size=10 | jq -r '.results|.[]|.name')

          LATEST=$(echo $IMAGE_TAGS | cut -d' ' --output-delimiter=$'\n' -f1- | sort -t. -k 1,1nr -k 2,2nr -k 3,3nr -k 4,4nr | head -n 1)

          CURRENT=`cat package.json | jq -r .version`
          if [ "$LATEST" != "$CURRENT" ]
          then
            echo Publishing "$CURRENT" version "${{ matrix.service }}" service.
            docker build . --file Dockerfile --build-arg GPR_TOKEN=${{secrets.GITHUB_TOKEN}} --tag lamk/"${{matrix.service}}":"$CURRENT"
            docker push lamk/"${{matrix.service}}":"$CURRENT"
          fi
        working-directory: ./packages/${{ matrix.service }}
