name: Publish services

on:
  push:
    branches:
      - master
    paths:
      - packages/data-api/**
      - packages/store-ui/**
      - packages/backstore-ui/**

jobs:
  publish-dockerfiles:
    name: Publish Service
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: ["data-api", "store-ui", "backstore-ui"]
    steps:
      - uses: actions/checkout@v1
      - uses: docker/login-action@v1
        with:
          registry: "registry.digitalocean.com/lamk"
          username: ${{ secrets.DO_REGISTRY_TOKEN }}
          password: ${{ secrets.DO_REGISTRY_TOKEN }}
      - run: |
          DOCKER_REPO="${{ matrix.service }}"
          DOCKER_TOKEN=${{ secrets.DO_REGISTRY_TOKEN }}

          API_ENDPOINT="https://api.digitalocean.com/v2"
          TAG_ENDPOINT="${API_ENDPOINT}/registry/lamk/repositories/${DOCKER_REPO}/tags"

          LATEST_TAG=$(curl -s -H "Authorization: Bearer ${DOCKER_TOKEN}" $TAG_ENDPOINT | jq -r '.tags[0].tag')
          CURRENT_TAG=`cat package.json | jq -r .version`

          if [ "$LATEST_TAG" != "$CURRENT_TAG" ]
          then
            echo Publishing "$CURRENT_TAG" version "${{ matrix.service }}" service.
            docker build . --file Dockerfile --build-arg GPR_TOKEN=${{secrets.GITHUB_TOKEN}} --tag registry.digitalocean.com/lamk/"${{matrix.service}}":"$CURRENT_TAG"
            docker push registry.digitalocean.com/lamk/"${{matrix.service}}":"$CURRENT_TAG"
          fi
        working-directory: ./packages/${{ matrix.service }}
